# This file is autogenerated by the command `make fix-copies`, do not edit.
# flake8: noqa
from ..utils import DummyObject, requires_backends


GREASELM_PRETRAINED_MODEL_ARCHIVE_LIST = None


class GreaseLMFeatureExtractor(metaclass=DummyObject):
    _backends = ["torch", "spacy"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch", "spacy"])


class GreaseLMForMultipleChoice(metaclass=DummyObject):
    _backends = ["scatter", "sparse"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["scatter", "sparse"])


class GreaseLMModel(metaclass=DummyObject):
    _backends = ["scatter", "sparse"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["scatter", "sparse"])


class GreaseLMProcessor(metaclass=DummyObject):
    _backends = ["torch", "spacy"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch", "spacy"])


class GreaseLMPreTrainedModel(metaclass=DummyObject):
    _backends = ["scatter", "sparse"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["scatter", "sparse"])


def load_tf_weights_in_greaselm(*args, **kwargs):
    requires_backends(load_tf_weights_in_greaselm, ["scatter", "sparse"])
